name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-express-app .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: |
        docker tag my-express-app:latest ${{ secrets.DOCKER_USERNAME }}/my-express-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-express-app:latest

    - name: Copy deploy script to EC2
      run: scp -i ${{ secrets.EC2_PRIVATE_KEY }} deploy.sh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_ELASTIC_IP }}:/home/${{ secrets.EC2_USERNAME }}/deploy.sh

    - name: Set execute permissions on deploy script
      run: ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_ELASTIC_IP }} 'chmod +x /home/${{ secrets.EC2_USERNAME }}/deploy.sh'

    - name: SSH into EC2 and deploy
      run: ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_ELASTIC_IP }} '/home/${{ secrets.EC2_USERNAME }}/deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.PORT }} ${{ secrets.SECRET_KEY }} ${{ secrets.MONGO_URI }} ${{ secrets.SMTP_HOST }} ${{ secrets.SMTP_PORT }} ${{ secrets.SMTP_USER }} ${{ secrets.SMTP_PASS }}'
